#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort1' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort1(n, arr):
    # Write your code here
    for i in range(n - 1, -1,-1):
        num = arr[i]
        for i in range(i - 1, -1, -1):
            if arr[i] > num:
                arr[i + 1] = arr[i]
                print(*arr)
                arr[i] = num
                
            else:
                arr[i + 1] = num
                break
    
    
                
    print(*arr)

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort1(n, arr)
